language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '12'
notifications:
  email: true
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
