language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '8'
notifications:
  email: false
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  script: scripts/deploy.sh
  provider: script
  skip_cleanup: true
  on:
    branch: master