sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "8"
notifications:
  email: false

deploy:
  script: scripts/deploy.sh
  provider: script
  skip_cleanup: true
  on:
    branch: master